# fly.toml app configuration file generated for d60e5406-587e-45fe-8826-c38f5e292056-0-membership on 2025-01-05T03:44:47-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'd60e5406-587e-45fe-8826-c38f5e292056-0-membership'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3011
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
